apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-repo-template
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-repo-template
  targetCPUUtilizationPercentage: 70
