apiVersion: v1
kind: Service
metadata:
  name: go-repo-template
  labels:
    app: go-repo-template
spec:
  selector:
    app: go-repo-template
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP